<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ352ozs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ352ozs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ352ozs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ352ozs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ352ozs\appDevDebugProjectContainer([
    'container.build_hash' => 'Z352ozs',
    'container.build_id' => '7cb05315',
    'container.build_time' => 1636045097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ352ozs');
