<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZgnvehu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZgnvehu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZgnvehu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZgnvehu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZgnvehu\appDevDebugProjectContainer([
    'container.build_hash' => 'Zgnvehu',
    'container.build_id' => '6c077a3b',
    'container.build_time' => 1636747423,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZgnvehu');
