<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC5zjaax\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC5zjaax/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC5zjaax.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC5zjaax\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC5zjaax\appProdProjectContainer([
    'container.build_hash' => 'C5zjaax',
    'container.build_id' => 'c73e4f07',
    'container.build_time' => 1635087593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC5zjaax');
