<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAqytlpf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAqytlpf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAqytlpf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAqytlpf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAqytlpf\appDevDebugProjectContainer([
    'container.build_hash' => 'Aqytlpf',
    'container.build_id' => '301b7eae',
    'container.build_time' => 1636043369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAqytlpf');
