<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgz3eef\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgz3eef/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXgz3eef.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXgz3eef\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXgz3eef\appDevDebugProjectContainer([
    'container.build_hash' => 'Xgz3eef',
    'container.build_id' => 'bc28f73d',
    'container.build_time' => 1636890812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgz3eef');
